### ISSUE TITLE
question about licensing for this project

### ISSUE THREAD

**Issue by terrance-wang** [VAST-AI-Research/TriplaneGaussian#10]
Just came across this project and played around with the huggingface demo! The results from your method look really good, and I was interested in playing with the code myself. I noticed that there wasn't a license file included in the repo though, do you guys plan on licensing this code at all? 

Thanks!

**Comment by pookiefoof** [comment]
Hi! Just added the license file to the repo. The code and model are both licensed under Apache 2.0.
