### ISSUE TITLE
There is no a_pikachu_with_smily_face_rgba.png in example_images 

### ISSUE THREAD

**Issue by linmi1** [VAST-AI-Research/TriplaneGaussian#12]
/home/stu/anaconda3/envs/TriplaneGaussian/bin/python infer.py --config config.yaml data.image_list=[example_images/a_pikachu_with_smily_face.webp,] --image_preprocess 
load model ckpt done.
/bin/sh: python: command not found
Traceback (most recent call last):
  File "infer.py", line 211, in <module>
    for batch in dataloader:
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home1/stu/linmi/TriplaneGaussian/tgs/data.py", line 229, in __getitem__
    Image.fromarray(imageio.v2.imread(img_path))
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home1/stu/linmi/TriplaneGaussian/example_images/a_pikachu_with_smily_face_rgba.png'

**Comment by linmi1** [comment]
> /home/stu/anaconda3/envs/TriplaneGaussian/bin/python infer.py --config config.yaml data.image_list=[example_images/a_pikachu_with_smily_face.webp,] --image_preprocess 加载模型 ckpt 已完成。 /bin/sh：python：找不到命令 回溯（最近一次调用）： 文件“infer.py”，第211行，用于 数据加载器中的批处理： 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3 .8/site-packages/torch/utils/data/dataloader.py”，第 681 行，下**一个** 数据 = self._next_data() 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site -packages/torch/utils/data/dataloader.py”，第 1376 行，在 _next_data 返回 self._process_data(data) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch /utils/data/dataloader.py”，第 1402 行，在 _process_data data.reraise() 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/_utils.py”中，第 461 行，在重新引发中 引发异常 FileNotFoundError：在 DataLoader 工作进程 0 中捕获 FileNotFoundError 。原始回溯（最近一次调用最后）： 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch /utils/data/_utils/worker.py”，第 302 行，在 _worker_loop data = fetcher.fetch(index) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/ utils/data/_utils/fetch.py​​”，第 49 行，在获取 数据 = [self.dataset[idx] for idx in possible_batched_index] 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site -packages/torch/utils/data/_utils/fetch.py​​”，第 49 行， 数据 = [self.dataset[idx] for idx in possible_batched_index] 文件“/home1/stu/linmi/TriplaneGaussian/tgs/data.py ”，第 229 行，在**getitem** Image.fromarray(imageio.v2.imread(img_path)) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/v2.py”中，第 359 行，在 imread 中 使用 imopen(uri, "ri", **imopen_args) 作为文件： File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/imopen. py”，第 113 行，在 imopen request = Request(uri, io_mode, format_hint=format_hint, extension=extension) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core /request.py”，第 247 行，在**init** self._parse_uri(uri) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/request.py”中，行407，在 _parse_uri 中 引发 FileNotFoundError("没有这样的文件：'%s'" % fn) FileNotFoundError：没有这样的文件：

I solve it by using the process in Dreamgaussian,but get this error:
load model ckpt done.
/bin/sh: python: command not found
Traceback (most recent call last):
  File "infer.py", line 213, in <module>
    model(batch)
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "infer.py", line 146, in forward
    out = self._forward(batch)
  File "infer.py", line 138, in _forward
    rend_out = self.renderer(scene_codes,
  File "/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/stu/linmi/TriplaneGaussian/tgs/models/renderer.py", line 409, in forward
    out_list.append(self.forward_single_batch(
  File "/home1/stu/linmi/TriplaneGaussian/tgs/models/renderer.py", line 377, in forward_single_batch
    out_list.append(self.forward_single_view(
  File "/home1/stu/linmi/TriplaneGaussian/tgs/models/renderer.py", line 282, in forward_single_view
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)

**Comment by linmi1** [comment]
> > /home/stu/anaconda3/envs/TriplaneGaussian/bin/python infer.py --config config.yaml data.image_list=[example_images/a_pikachu_with_smily_face.webp,] --image_preprocess 加载模型 ckpt 已完成。 /bin/sh：python ：缺少命令回溯（最近一次调用）：文件“infer.py”，第211行，用于数据加载器中的批处理：文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3 . 8/site-packages/torch/utils/data/dataloader.py”，第681行，下**一个**data = self._next_data()文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site -packages/torch/utils/data/dataloader.py”，第 1376 行，在 _next_data 返回 self._process_data(data) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/ torch /utils/data/dataloader.py”，第 1402 行，在 _process_data data.reraise() 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/_utils.py ”中，第461行，在重新引发中引发异常 FileNotFoundError：在 DataLoader 工作进程 0 中捕获 FileNotFoundError 。 原始回溯（最近一次调用最后）：文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.1” 8/site-packages/torch /utils/data/_utils/worker.py”，第302行，在_worker_loop data = fetcher.fetch(index)“文件/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3. 8/site-packages/torch/ utils/data/_utils/fetch.py​​​​”，第49行，在获取数据 = [self.dataset[idx] for idx in possible_batched_index]文件“/home/stu/anaconda3/ envs/TriplaneGaussian/lib/python3.8/site -packages/torch/utils/data/_utils/fetch.py​​​​”，第 49 行， Data = [self.dataset[idx] for idx in possible_batched_index] 文件“/ home1/stu/linmi/TriplaneGaussian/tgs/data.py ”，第 229 行，在**getitem** Image.fromarray(imageio.v2.imread(img_path)) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3 .8/site-packages/imageio/v2.py”中，第359行，在 imread 使用中 imopen(uri, "ri", **imopen_args) 作为文件： File "/home/stu/anaconda3/envs/TriplaneGaussian/lib /python3.8/site-packages/imageio/core/imopen。py”，第 113 行，在 imopen request = Request(uri, io_mode, format_hint=format_hint, extension=extension) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/ core /request.py”，第 247 行，在**init** self._parse_uri(uri) 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/imageio/core/request. py”中，行407，在 _parse_uri 中 引发 FileNotFoundError("没有这样的文件：'%s'" % fn) FileNotFoundError：没有这样的文件：
> 
> 我通过使用Dreamgaussian中的过程解决了这个问题，但得到这个错误： 加载模型ckpt完成。 /bin/sh：python：找不到命令 回溯（最近一次调用）： 文件“infer.py”，第 213 行， 模型（批处理） 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3. 8/site-packages/torch/nn/modules/module.py”，第 1130 行，在 _call_impl 返回forward_call(*input, **kwargs) 文件“infer.py”，第 146 行，在forward out = self._forward(批处理） 文件“infer.py”，第138行，在_forward rend_out = self.renderer（scene_codes， 文件“/home/stu/anaconda3/envs/TriplaneGaussian/lib/python3.8/site-packages/torch/nn/modules”中/module.py”，第 1130 行，在 _call_impl returnforward_call(*input, **kwargs) 文件“/home1/stu/linmi/TriplaneGaussian/tgs/models/renderer.py”，第 409 行，在forward out_list.append( self.forward_single_batch（ 文件“/home1/stu/linmi/TriplaneGaussian/tgs/models/renderer.py”，第377行，在forward_single_batch out_list.append（self.forward_single_view（ 文件“/home1/stu/linmi/TriplaneGaussian/tgs/） models/renderer.py"，第 282 行，在forward_single_view render_image，radii = rasterizer( ValueError: 太多值无法解压（预期为 2）

I find that I install the wrong pack about diff-gaussian-rasterization

**Comment by hengyu-wang** [comment]
Hello, I would like to know how you use DreamGaussian to solve this issue: "There is no a_pikachu_with_smily_face_rgba.png."
